SET(LIBGP_SRC
  src/cov.cc
  src/cov_factory.cc
  src/cov_linear_ard.cc
  src/cov_linear_one.cc
  src/cov_matern3_iso.cc
  src/cov_matern5_iso.cc
  src/cov_noise.cc
  src/cov_rq_iso.cc
  src/cov_periodic_matern3_iso.cc
  src/cov_periodic.cc
  src/cov_se_ard.cc
  src/cov_se_iso.cc
  src/cov_sum.cc
  src/cov_prod.cc
  src/gp.cc
  src/gp_utils.cc
  src/sampleset.cc
  src/rprop.cc
  src/input_dim_filter.cc
  src/cg.cc
)

SET(LIBGP_INTERFACES 
  include/libgp/cov.h
  include/libgp/cov_factory.h
  include/libgp/cov_linear_ard.h
  include/libgp/cov_linear_one.h
  include/libgp/cov_matern3_iso.h
  include/libgp/cov_matern5_iso.h
  include/libgp/cov_noise.h
  include/libgp/cov_rq_iso.h
  include/libgp/cov_periodic_matern3_iso.h
  include/libgp/cov_periodic.h
  include/libgp/cov_se_ard.h
  include/libgp/cov_se_iso.h
  include/libgp/cov_sum.h
  include/libgp/cov_prod.h
  include/libgp/gp.h
  include/libgp/gp_utils.h
  include/libgp/sampleset.h
  include/libgp/rprop.h
  include/libgp/input_dim_filter.h
  include/libgp/cg.h
)
